package wired:wds;

world all {
  import api;
  import types;
}

interface api {
  use types.{wds};
  use wired:error/types.{error};

  get-wds: func() -> result<wds, error>;
}

interface types {
  type did  = string;
  type hash = list<u8>;

  record query-filter {
    creator: option<did>,
    schemas: option<list<hash>>,
  }

  resource query-future {
    poll: func() -> option<result<list<hash>>>;
  }

  resource read-future {
    poll: func() -> option<result<list<u8>>>;
  }

  resource blob-future {
    poll: func() -> option<result<list<u8>>>;
  }

  resource wds {
    query:    func(filter: option<query-filter>) -> query-future;
    read:     func(record-id: hash) -> read-future;
    get-blob: func(blob-id: hash) -> blob-future;
  }
}
