[package]
build                = "build.rs"
edition.workspace    = true
license.workspace    = true
name                 = "unavi-client"
publish              = false
repository.workspace = true
version.workspace    = true

[features]
default = ["dev_tools"]
dev_tools = [
  "bevy/bevy_dev_tools",
  "bevy/debug",
  "dep:bevy-inspector-egui",
  "unavi-input/egui-filter",
  "unavi-script/debug",
]
mdns = ["bevy-iroh/mdns"]
webgpu = ["bevy/webgpu", "unavi-agent/webgpu", "unavi-avatar/webgpu"]

[lints]
workspace = true

[build-dependencies]
embed-resource.workspace = true

[dependencies]
anyhow.workspace        = true
async-channel.workspace = true
avian3d.workspace       = true
bevy                    = { default-features = true, features = ["https", "jpeg"], workspace = true }
bevy-hsd.path           = "../bevy-hsd"
bevy-inspector-egui     = { optional = true, workspace = true }
bevy-iroh.path          = "../bevy-iroh"
bevy-wds.path           = "../bevy-wds"
bevy_vrm.workspace      = true
bitflags                = "2.11.0"
blake3.workspace        = true
clap.workspace          = true
image                   = { default-features = false, features = ["png"], workspace = true }
iroh.workspace          = true
log                     = { features = ["max_level_debug", "release_max_level_warn"], version = "*" }
parking_lot.workspace   = true
tracing                 = { features = ["max_level_debug", "release_max_level_warn"], workspace = true }
unavi-agent.path        = "../unavi-agent"
unavi-assets.path       = "../unavi-assets"
unavi-avatar.path       = "../unavi-avatar"
unavi-identity.path     = "../unavi-identity"
unavi-input.path        = "../unavi-input"
unavi-manifold.path     = "../unavi-manifold"
unavi-script.path       = "../unavi-script"
unavi-space.path        = "../unavi-space"
unavi-util.path         = "../unavi-util"
unavi-wasm-compat.path  = "../unavi-wasm-compat"
web-time                = "1.1.0"
winit                   = { default-features = false, version = "0.30.13" }
wired-schemas.path      = "../wired-schemas"
xdid.workspace          = true
zeroize.workspace       = true

[target.'cfg(target_family = "wasm")'.dependencies]
reqwest.workspace = true
web-sys           = { features = ["Location", "UrlSearchParams"], workspace = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
bevy_mod_openxr         = "0.5.0"
bevy_mod_xr.workspace   = true
bevy_xr_utils.workspace = true
directories.workspace   = true
reqwest                 = { features = ["blocking"], workspace = true }
