[project]
name     = "unavi-client"
revision = "1.0"

[profiles.default]
UNAVI_SYNC_TARGETS = { default = "did:web:node.unavi.xyz", description = "Comma separated DIDs of the servers this client follows" }

[profiles.development]
UNAVI_SYNC_TARGETS = { default = "did:web:localhost%3A5000" }
