[package]
edition.workspace    = true
license.workspace    = true
name                 = "unavi-gauntlet-tool"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow.workspace      = true
blake3.workspace      = true
postcard.workspace    = true
serde                 = { features = ["derive"], workspace = true }
wired-prelude.path    = "../wired-prelude"
wit-bindgen.workspace = true
