[package]
name = "unavi-world-host"
publish = false
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
axum-server.workspace = true
axum.workspace = true
base64.workspace = true
dwn.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
wired-social = { path = "../wired-social" }
