[package]
edition.workspace    = true
license.workspace    = true
name                 = "wds-schema"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[features]
default    = ["validation"]
validation = ["dep:loro"]

[dependencies]
blake3.workspace    = true
loro                = { optional = true, workspace = true }
postcard.workspace  = true
ron.workspace       = true
serde               = { features = ["derive"], workspace = true }
smol_str.workspace  = true
thiserror.workspace = true
