[package]
edition.workspace    = true
license.workspace    = true
name                 = "wired-kv"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[dependencies]
postcard            = { features = ["use-std"], workspace = true }
serde               = { features = ["derive"], workspace = true }
thiserror.workspace = true
