- match:
    dependency_name: typescript
    update_type: semver:patch

- match:
    dependency_name: three
    update_type: semver:patch

- match:
    dependency_name: aws-sdk
    update_type: semver:patch
