[graph]
all-features = true
targets = [
  "wasm32-unknown-unknown",
  "x86_64-apple-darwin",
  "x86_64-pc-windows-msvc",
  "x86_64-unknown-linux-gnu",
]

[licenses]
version = 2
allow = [
  "Apache-2.0 WITH LLVM-exception",
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "BSL-1.0",
  "CC0-1.0",
  "ISC",
  "MIT",
  "MIT-0",
  "MPL-2.0",
  "Unicode-3.0",
  "Unlicense",
  "Zlib",
]

[bans]
multiple-versions = "warn"
deny = [
  { name = "bevy", deny-multiple-versions = true },
  { name = "tokio", deny-multiple-versions = true },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = [
  "https://github.com/unavi-xyz/dwn",
  "https://github.com/vincent-herlemont/native_db",
]
