[package]
edition.workspace    = true
license.workspace    = true
name                 = "unavi-vui-nav"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
blake3.workspace      = true
wired-prelude.path    = "../wired-prelude"
wired-schemas.path    = "../../crates/wired-schemas"
wit-bindgen.workspace = true
