[package]
edition.workspace    = true
license.workspace    = true
name                 = "unavi-physics"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[dependencies]
avian3d.workspace = true
bevy.workspace    = true
obvhs             = "0.3.2"
