[package]
edition.workspace    = true
license.workspace    = true
name                 = "unavi-vui"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow.workspace      = true
arrayvec              = { features = ["serde"], workspace = true }
serde.workspace       = true
smol_str.workspace    = true
wired-math.path       = "../wired-math"
wired-prelude.path    = "../wired-prelude"
wired-scene.path      = "../wired-scene"
wit-bindgen.workspace = true
