[package]
edition.workspace    = true
license.workspace    = true
name                 = "unavi-vui"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow.workspace      = true
arrayvec.workspace    = true
smol_str.workspace    = true
wired-guest.path      = "../wired-guest"
wit-bindgen.workspace = true
