[package]
edition.workspace    = true
license.workspace    = true
name                 = "wds"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[dependencies]
anyhow.workspace      = true
blake3.workspace      = true
bytes                 = "1.11.1"
derive_more           = { features = ["debug"], version = "2.1.1" }
futures.workspace     = true
iroh.workspace        = true
irpc                  = "0.13.0"
irpc-iroh             = "0.13.0"
jose-jwk              = "0.1.2"
loro.workspace        = true
lorosurgeon.workspace = true
n0-error              = { features = ["anyhow"], version = "0.1.3" }
n0-future.workspace   = true
p256                  = { default-features = false, features = ["ecdsa"], version = "0.13.2" }
p384                  = { default-features = false, features = ["ecdsa"], version = "0.13.1" }
parking_lot.workspace = true
postcard.workspace    = true
rand.workspace        = true
rusqlite              = { features = ["bundled"], version = "0.39" }
scc                   = "3.6.12"
serde.workspace       = true
signature             = "2.2.0"
smol_str              = "0.3.6"
thiserror             = "2.0.18"
time.workspace        = true
tokio.workspace       = true
tokio-util            = { features = ["codec"], workspace = true }
tracing.workspace     = true
wds-schema.path       = "../wds-schema"
wired-records.path    = "../wired-records"
wired-schemas.path    = "../wired-schemas"
xdid.workspace        = true

[target.'cfg(target_family = "wasm")'.dependencies]
iroh-blobs = { features = ["hide-proto-docs"], workspace = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
iroh-blobs = { default-features = true, workspace = true }

[target.'cfg(not(target_family = "wasm"))'.dev-dependencies]
axum.workspace = true
rstest         = "0.26.1"
tokio          = { features = ["macros", "rt-multi-thread"], workspace = true }
tracing-test   = { features = ["no-env-filter"], workspace = true }
