package example:wired-input;

world script {
    include wired:script/script; 

    import unavi:shapes/api;
    import wired:gltf/material;
    import wired:gltf/mesh;
    import wired:gltf/node;
    import wired:input/handler;
    import wired:log/api;
}
