[package]
name = "unavi-web-app"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
http = "0.2.9"
leptos = "0.5.1"
leptos_axum = { version = "0.5.1", optional = true }
leptos_meta = "0.5.1"
leptos_router = "0.5.1"
thiserror = "1.0.50"

[features]
default = []
hydrate = ["leptos/hydrate", "leptos_meta/hydrate", "leptos_router/hydrate"]
ssr = ["leptos/ssr", "leptos_meta/ssr", "leptos_router/ssr", "dep:leptos_axum"]
