package wired:script;

world guest {
  export guest-api;
}

interface guest-api {
  /// Called once on instantiation.
  init: func();

  /// Called every frame, before rendering.
  update: func();

  /// Called on a fixed interval.
  fixed-update: func();
}
