[package]
edition.workspace    = true
license.workspace    = true
name                 = "bevy-iroh"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[dependencies]
anyhow.workspace       = true
bevy.workspace         = true
iroh                   = { features = ["address-lookup-mdns"], workspace = true }
n0-future.workspace    = true
tracing.workspace      = true
unavi-util.path        = "../unavi-util"
unavi-wasm-compat.path = "../unavi-wasm-compat"
