[package]
edition.workspace    = true
license.workspace    = true
name                 = "bevy-iroh"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[dependencies]
anyhow.workspace        = true
async-channel.workspace = true
bevy.workspace          = true
bevy-async.path         = "../bevy-async"
bytes.workspace         = true
iroh.workspace          = true
iroh-blobs              = { features = ["hide-proto-docs"], workspace = true }
n0-future.workspace     = true
thiserror.workspace     = true
tokio.workspace         = true
tracing.workspace       = true
unavi-store.path        = "../unavi-store"

[dev-dependencies]
iroh-docs.workspace = true
