[package]
edition.workspace    = true
license.workspace    = true
name                 = "wired-records"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[features]
default = []
loro    = ["dep:anyhow", "dep:loro", "dep:loro-surgeon"]

[dependencies]
blake3.workspace = true
serde            = { features = ["derive"], workspace = true }
xdid.workspace   = true

anyhow       = { optional = true, workspace = true }
loro         = { optional = true, workspace = true }
loro-surgeon = { optional = true, path = "../loro-surgeon" }

[dev-dependencies]
loro = { workspace = true }
