[package]
edition.workspace    = true
license.workspace    = true
name                 = "wired-records"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[features]
default = []
loro    = ["dep:anyhow", "dep:blake3", "dep:loro", "dep:loro-surgeon", "dep:xdid"]

[dependencies]
postcard = { workspace = true }
serde    = { features = ["derive"], workspace = true }

anyhow       = { optional = true, workspace = true }
blake3       = { optional = true, workspace = true }
loro         = { optional = true, workspace = true }
loro-surgeon = { optional = true, path = "../loro-surgeon" }
xdid         = { optional = true, workspace = true }

[dev-dependencies]
loro = { workspace = true }
