const CUID_LENGTH = 25;

export const PROJECT_ID_LENGTH = 21;
export const PUBLICATION_ID_LENGTH = CUID_LENGTH;
export const PUBLISHED_MODEL_ID_LENGTH = CUID_LENGTH;
export const ASSET_ID_LENGTH = CUID_LENGTH;
export const MAX_NAME_LENGTH = 80;
export const MAX_DESCRIPTION_LENGTH = 1200;
