package unavi:log;

world lib {
  export api;
}

interface api {
  enum log-level {
    debug,
    info,
    warn,
    error
  }

  // Logs a message with the given log level.
  log: func(level: log-level, msg: string);
}
