[package]
edition.workspace    = true
license.workspace    = true
name                 = "unavi-secrets"
publish              = false
repository.workspace = true
version.workspace    = true

[lib]
proc-macro = true

[lints]
workspace = true

[dependencies]
anyhow.workspace     = true
proc-macro2          = "1.0.107"
quote                = "1.0.47"
secretspec.workspace = true
syn                  = "3.0.3"

[dev-dependencies]
prettyplease = "0.3.0"
syn          = { features = ["full"], version = "3.0.3" }
