[package]
name = "wired-social"
publish = false
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
dwn.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
jsonschema = "0.26.1"
