[package]
edition.workspace    = true
license.workspace    = true
name                 = "hsd-cli"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
blake3.workspace = true
clap.workspace   = true
hsd              = { path = "../hsd" }
toml             = "1.1.2"
