[package]
edition.workspace    = true
license.workspace    = true
name                 = "hsd-cli"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[dependencies]
anyhow.workspace     = true
blake3.workspace     = true
clap.workspace       = true
hsd.path             = "../hsd"
ron                  = { features = ["indexmap"], workspace = true }
serde                = { features = ["derive"], workspace = true }
serde_with.workspace = true
toml.workspace       = true
