[package]
edition.workspace    = true
license.workspace    = true
name                 = "test-macros"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "3.5.0"
quote            = "1.0.45"
syn              = { features = ["full"], version = "2.0.117" }
