[package]
edition.workspace    = true
license.workspace    = true
name                 = "wired-math"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[dependencies]
glam            = { features = ["serde"], workspace = true }
serde.workspace = true
