[package]
edition.workspace    = true
license.workspace    = true
name                 = "bevy-hsd"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[dependencies]
anyhow.workspace        = true
async-channel.workspace = true
avian3d.workspace       = true
bevy.workspace          = true
bevy-wds.path           = "../bevy-wds"
blake3.workspace        = true
bytemuck                = "1.25.0"
bytes.workspace         = true
hsd.path                = "../hsd"
image                   = { features = ["jpeg", "png"], workspace = true }
iroh-blobs              = { features = ["hide-proto-docs"], workspace = true }
iroh-docs.workspace     = true
postcard.workspace      = true
smol_str.workspace      = true
thiserror.workspace     = true
unavi-physics.path      = "../unavi-physics"
unavi-quota             = { path = "../unavi-quota", version = "0.0.16" }
unavi-util.path         = "../unavi-util"
wds.path                = "../wds"

[dev-dependencies]
bevy_panorbit_camera.workspace = true
iroh-blobs.workspace           = true
naga                           = { default-features = false, features = ["wgsl-in"], version = "29.0.4" }
rstest.workspace               = true
tracing.workspace              = true
tracing-test                   = { features = ["no-env-filter"], workspace = true }
wds.path                       = "../wds"
