[package]
edition.workspace    = true
license.workspace    = true
name                 = "bevy-hsd"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[dependencies]
anyhow.workspace        = true
async-channel.workspace = true
avian3d.workspace       = true
bevy.workspace          = true
bevy-wds.path           = "../bevy-wds"
blake3.workspace        = true
bytemuck.workspace      = true
bytes.workspace         = true
hsd.path                = "../hsd"
image                   = { default-features = false, features = ["jpeg", "png", "webp"], workspace = true }
loro.workspace          = true
loro-surgeon.path       = "../loro-surgeon"
smol_str.workspace      = true
unavi-util.path         = "../unavi-util"
wds.path                = "../wds"
wired-records           = { features = ["loro"], path = "../wired-records" }

[dev-dependencies]
bevy                           = { features = ["debug"], workspace = true }
bevy_panorbit_camera.workspace = true
iroh-blobs                     = { default-features = true, workspace = true }
loro-surgeon.path              = "../loro-surgeon"
