[package]
edition.workspace    = true
license.workspace    = true
name                 = "wired-state-macro"
publish              = false
repository.workspace = true
version.workspace    = true

[lib]
proc-macro = true

[lints]
workspace = true

[dependencies]
anyhow.workspace      = true
proc-macro2.workspace = true
quote.workspace       = true
syn                   = { features = ["full"], workspace = true }

[dev-dependencies]
prettyplease.workspace = true
