[package]
edition.workspace    = true
license.workspace    = true
name                 = "unavi-devtools"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[dependencies]
async-channel.workspace = true
bevy                    = { features = ["experimental_bevy_feathers"], workspace = true }
