[package]
edition.workspace    = true
license.workspace    = true
name                 = "hsd"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[dependencies]
anyhow.workspace      = true
bevy.workspace        = true
loro.workspace        = true
lorosurgeon.workspace = true
ron.workspace         = true
serde                 = { features = ["derive"], workspace = true }
serde_with.workspace  = true
smol_str.workspace    = true
wired-records         = { features = ["loro"], path = "../wired-records" }
