[package]
edition.workspace    = true
license.workspace    = true
name                 = "hsd"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[dependencies]
bevy.workspace       = true
blake3.workspace     = true
loro.workspace       = true
loro-surgeon.path    = "../loro-surgeon"
ron.workspace        = true
serde                = { features = ["derive"], workspace = true }
serde_with.workspace = true
smol_str.workspace   = true
wired-records        = { features = ["loro"], path = "../wired-records" }
