package example:wired-gltf;

world script {
    include wired:script/script; 

    import unavi:shapes/api;
    import wired:gltf/material;
    import wired:gltf/mesh;
    import wired:gltf/node;
    import wired:log/api;
}
