package wired:prelude;

world types {
  import wired:agent/types;
  import wired:event/types;
  import wired:input/types;
  import wired:kv/types;
  import wired:math/types;
  import wired:scene/types;
  import wired:wds/types;
}

world api {
  import wired:event/api;
  import wired:input/api;
  import wired:kv/api;
  import wired:scene/api;
}

world api-secure {
  import wired:agent/api;
  import wired:input/api;
  import wired:wds/api;
}

world lib {
  include api;
  include types;
}

world lib-secure {
  include api-secure;
  include lib;
}

world script {
  include lib;
  include wired:script/guest;
}

world script-secure {
  include lib-secure;
  include wired:script/guest;
}
