[package]
edition.workspace    = true
license.workspace    = true
name                 = "unavi-vui"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[dependencies]
arrayvec           = { features = ["serde"], version = "0.7.8" }
serde.workspace    = true
smol_str.workspace = true
wired-math.path    = "../../wasm/wired-math"
wired-scene.path   = "../../wasm/wired-scene"
