[package]
edition.workspace    = true
license.workspace    = true
name                 = "unavi-gate"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
postcard.workspace          = true
unavi-portal-protocol.path  = "../../crates/unavi-portal-protocol"
wired-prelude.path          = "../wired-prelude"
wit-bindgen.workspace       = true
