package unavi:scene;

world guest {
    include wired:scene/prelude;

    export api;
}

interface api {
  use wired:math/types.{transform};
  use wired:scene/node.{node};

  resource root {
    list-scenes: static func() -> list<scene>;
    // Add a scene to the root glXF.
    // This will make the scene a part of the game world.
    add-scene: static func(value: borrow<scene>);
    remove-scene: static func(value: borrow<scene>);
  }

  // An abstraction over the `wired:scene` glTF and glXF APIs.
  // New scenes are stored as separate glTF documents.
  resource scene {
    constructor();

    list-nodes: func() -> list<node>;
    // Creates a node within the scene.
    create-node: func() -> node;
    add-node: func(value: borrow<node>);
    remove-node: func(value: borrow<node>);

    transform: func() -> transform;
    set-transform: func(value: transform);

    active: func() -> bool;
    set-active: func(value: bool);
  }
}
