[package]
edition.workspace    = true
license.workspace    = true
name                 = "unavi-policy"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[dependencies]
anyhow.workspace      = true
bevy                  = { default-features = true, workspace = true }
bevy-hsd.path         = "../bevy-hsd"
hsd.path              = "../hsd"
blake3.workspace      = true
iroh-docs.workspace   = true
parking_lot.workspace = true
rand.workspace        = true
serde                 = { features = ["derive"], workspace = true }
thiserror.workspace   = true
toml.workspace        = true
tracing.workspace     = true
unavi-quota.path      = "../unavi-quota"
xdid.workspace        = true
