[package]
edition.workspace    = true
license.workspace    = true
name                 = "unavi-policy"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[dependencies]
anyhow.workspace      = true
bevy                  = { default-features = true, workspace = true }
bevy-hsd.path         = "../bevy-hsd"
hsd.path              = "../hsd"
iroh.workspace        = true
iroh-docs.workspace   = true
parking_lot.workspace = true
serde                 = { features = ["derive"], workspace = true }
thiserror.workspace   = true
toml.workspace        = true
tracing.workspace     = true
unavi-identity.path   = "../unavi-identity"
unavi-store.path      = "../unavi-store"
web-time.workspace    = true
xdid.workspace        = true

[target.'cfg(not(target_family = "wasm"))'.dependencies]
sysinfo = { default-features = false, features = ["system"], version = "0.38.4" }

[dev-dependencies]
blake3.workspace = true
