[package]
description          = "Proc-macro support for loro-surgeon."
edition.workspace    = true
license.workspace    = true
name                 = "loro-surgeon-derive"
repository.workspace = true
version.workspace    = true

[lib]
proc-macro = true

[dependencies]
proc-macro2     = "1.0.107"
quote.workspace = true
syn             = { features = ["extra-traits"], workspace = true }

[lints]
workspace = true
