[package]
name = "unavi-app"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
bevy = "0.12.0"
bevy_rapier3d = { version = "0.23.0", features = ["simd-stable"] }
bevy_vrm = "0.0.5"
wired-protocol = { path = "../wired-protocol" }
