[package]
edition.workspace    = true
license.workspace    = true
name                 = "test-log"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
bincode.workspace     = true
wired-ecs.path        = "../../crates/wired-ecs"
wit-bindgen.workspace = true
