[package]
edition.workspace    = true
license.workspace    = true
name                 = "unavi-grab"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[dependencies]
avian3d.workspace   = true
bevy.workspace      = true
bevy-hsd.path       = "../bevy-hsd"
iroh-docs.workspace = true
unavi-input.path    = "../unavi-input"
unavi-policy.path   = "../unavi-policy"
unavi-space.path    = "../unavi-space"
unavi-util          = { path = "../unavi-util", version = "0.0.16" }

[dev-dependencies]
unavi-physics = { path = "../unavi-physics" }
