[package]
edition.workspace    = true
license.workspace    = true
name                 = "unavi"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
avian3d.workspace = true
bevy = { default-features = true, features = ["wayland"], workspace = true }
bevy_mod_openxr = "0.3.0"
directories.workspace = true
image = { default-features = false, features = ["png"], version = "0.25.6" }
log = { features = [
  "max_level_debug",
  "release_max_level_info",
], version = "*" }
unavi-input.path = "../unavi-input"
unavi-player.path = "../unavi-player"
unavi-script.path = "../unavi-script"
winit = { default-features = false, version = "0.30.11" }
