[package]
edition.workspace    = true
license.workspace    = true
name                 = "unavi"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
avian3d.workspace = true
bevy = { default-features = true, features = ["wayland"], workspace = true }
directories.workspace = true
dwn = { version = "0.3.0", git = "https://github.com/unavi-xyz/dwn" }
image = { default-features = false, features = ["png"], version = "0.25.8" }
log = { features = [
  "max_level_debug",
  "release_max_level_info",
], version = "*" }
unavi-input.path = "../unavi-input"
unavi-player.path = "../unavi-player"
unavi-script.path = "../unavi-script"
winit = { default-features = false, version = "0.30.12" }
xdid = { version = "0.3.0", git = "https://github.com/unavi-xyz/dwn" }
zeroize = "1.8.2"
