package unavi:ui;

world guest {
    import unavi:shapes/api;

    export button;
}

world prelude {
  import button;
}

interface button {
  use unavi:layout/container.{container};

  // 3D interactable button.
  // Fills the space of its root container.
  resource button {
    constructor(root: container);

    root: func() -> container;
  }
}

