//! Checks a downloaded release asset against a `SHA256SUMS` manifest
//! published alongside it, so a compromised or truncated download is caught
//! before anything in the install directory is touched.

use std::{
    collections::HashMap,
    fmt::Write as _,
    fs,
    path::Path,
};

use anyhow::{
    Context,
    bail,
};
use sha2::{
    Digest,
    Sha256,
};

/// Checksums for every asset in a release, keyed by file name.
pub struct Manifest {
    checksums: HashMap<String, String>,
}

impl Manifest {
    /// Parses the `sha256sum`-style format (`<64 hex chars>  <file name>`,
    /// optionally with a leading `*` for binary mode). Any line that is not
    /// blank, a `#` comment, or a well-formed entry is an error: a truncated
    /// or corrupted manifest must not silently check nothing.
    pub fn parse(text: &str) -> anyhow::Result<Self> {
        let mut checksums = HashMap::new();

        for (index, line) in text.lines().enumerate() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }

            let lineno = index + 1;
            let (hash, name) = line
                .split_once(char::is_whitespace)
                .with_context(|| format!("malformed checksum manifest at line {lineno}"))?;

            let hash = hash.trim();
            if hash.len() != 64 || !hash.bytes().all(|b| b.is_ascii_hexdigit()) {
                bail!("malformed checksum manifest at line {lineno}: not a sha-256 digest");
            }

            let name = name.trim_start_matches([' ', '*']).trim();
            if name.is_empty() {
                bail!("malformed checksum manifest at line {lineno}: missing file name");
            }

            checksums.insert(name.to_string(), hash.to_ascii_lowercase());
        }

        Ok(Self { checksums })
    }

    /// Hashes `path` and compares it against the manifest entry for `name`.
    /// A missing entry is an error, the same as a mismatch: an asset added
    /// without a manifest entry must not install silently.
    pub fn verify(&self, name: &str, path: &Path) -> anyhow::Result<()> {
        let expected = self
            .checksums
            .get(name)
            .with_context(|| format!("no checksum entry for {name}"))?;

        let actual = hash_file(path)?;
        if actual != *expected {
            bail!("checksum mismatch for {name}: expected {expected}, got {actual}");
        }

        Ok(())
    }
}

fn hash_file(path: &Path) -> anyhow::Result<String> {
    let bytes = fs::read(path).with_context(|| format!("failed to read {}", path.display()))?;

    let mut hasher = Sha256::new();
    hasher.update(&bytes);
    let digest = hasher.finalize();

    let mut hex = String::with_capacity(64);
    for byte in digest {
        write!(&mut hex, "{byte:02x}").expect("writing to a String never fails");
    }

    Ok(hex)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_sha256sum_format() {
        let hash = "a".repeat(64);
        let text = format!("{hash}  unavi-client.AppImage\n");
        let manifest = Manifest::parse(&text).expect("well-formed manifest");
        assert_eq!(manifest.checksums.get("unavi-client.AppImage"), Some(&hash));
    }

    #[test]
    fn skips_blank_lines_and_comments() {
        let hash = "b".repeat(64);
        let text = format!("# generated by release.yml\n\n{hash}  asset.bin\n");
        let manifest = Manifest::parse(&text).expect("well-formed manifest");
        assert_eq!(manifest.checksums.len(), 1);
    }

    #[test]
    fn rejects_malformed_manifest() {
        assert!(Manifest::parse("not-a-checksum-line").is_err());
        assert!(Manifest::parse("not-hex-but-right-length-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa file").is_err());
        assert!(Manifest::parse(&format!("{}  \n", "c".repeat(64))).is_err());
    }

    #[test]
    fn verify_accepts_matching_hash() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("asset.bin");
        fs::write(&path, b"hello world").expect("write asset");

        let hash = hash_file(&path).expect("hash asset");
        let manifest =
            Manifest::parse(&format!("{hash}  asset.bin\n")).expect("well-formed manifest");

        manifest
            .verify("asset.bin", &path)
            .expect("hash should match");
    }

    #[test]
    fn verify_rejects_mismatch() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("asset.bin");
        fs::write(&path, b"hello world").expect("write asset");

        let bogus = "0".repeat(64);
        let manifest =
            Manifest::parse(&format!("{bogus}  asset.bin\n")).expect("well-formed manifest");

        let err = manifest
            .verify("asset.bin", &path)
            .expect_err("hash should not match");
        assert!(err.to_string().contains("mismatch"));
    }

    #[test]
    fn verify_rejects_missing_entry() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("asset.bin");
        fs::write(&path, b"hello world").expect("write asset");

        let manifest = Manifest::parse("").expect("empty manifest parses");

        let err = manifest
            .verify("asset.bin", &path)
            .expect_err("entry should be missing");
        assert!(err.to_string().contains("no checksum entry"));
    }
}
