[package]
edition.workspace    = true
license.workspace    = true
name                 = "unavi-gauntlet"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow.workspace         = true
unavi-gauntlet-menu.path = "../../crates/unavi-gauntlet-menu"
wired-prelude.path       = "../wired-prelude"
wired-schemas.path       = "../../crates/wired-schemas"
wit-bindgen.workspace    = true
