[package]
edition.workspace    = true
license.workspace    = true
name                 = "unavi-input"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[features]
default     = []
devtools    = ["dep:unavi-devtools"]
egui-filter = ["dep:bevy_egui"]

[dependencies]
avian3d.workspace     = true
bevy                  = { default-features = true, features = ["serialize"], workspace = true }
bevy_egui             = { optional = true, version = "0.40.1" }
parking_lot.workspace = true
ron.workspace         = true
serde.workspace       = true
unavi-devtools        = { optional = true, path = "../unavi-devtools" }
uuid                  = "1.24.0"

[target.'cfg(target_family = "wasm")'.dependencies]
wasm-bindgen.workspace = true
web-sys                = { features = ["AddEventListenerOptions", "Document", "Element", "EventTarget", "HtmlElement", "KeyboardEvent", "Navigator", "Window"], workspace = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
bevy_mod_xr.workspace   = true
bevy_xr_utils.workspace = true
unavi-util.path         = "../unavi-util"

[dev-dependencies]
rstest.workspace = true
