[package]
edition.workspace    = true
license.workspace    = true
name                 = "bevy-wds"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[dependencies]
anyhow.workspace        = true
async-channel.workspace = true
bevy.workspace          = true
blake3.workspace        = true
bytes.workspace         = true
iroh-base.workspace     = true
loro.workspace          = true
n0-future.workspace     = true
smol_str.workspace      = true
tokio.workspace         = true
unavi-util.path         = "../unavi-util"
wds.path                = "../wds"
xdid.workspace          = true
