[package]
edition.workspace    = true
license.workspace    = true
name                 = "bevy-wds"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[dependencies]
anyhow.workspace        = true
async-channel.workspace = true
bevy.workspace          = true
blake3.workspace        = true
bytes.workspace         = true
iroh.workspace          = true
iroh-blobs              = { features = ["hide-proto-docs"], workspace = true }
iroh-docs.workspace     = true
iroh-gossip.workspace   = true
n0-future.workspace     = true
tokio.workspace         = true
unavi-util.path         = "../unavi-util"
wds.path                = "../wds"
wired-registry.path     = "../wired-registry"
xdid.workspace          = true
