/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace DataTypes {
  export type EIP712SignatureStruct = {
    v: BigNumberish;
    r: BytesLike;
    s: BytesLike;
    deadline: BigNumberish;
  };

  export type EIP712SignatureStructOutput = [
    number,
    string,
    string,
    BigNumber
  ] & { v: number; r: string; s: string; deadline: BigNumber };

  export type SetProfileMetadataWithSigDataStruct = {
    user: string;
    profileId: BigNumberish;
    metadata: string;
    sig: DataTypes.EIP712SignatureStruct;
  };

  export type SetProfileMetadataWithSigDataStructOutput = [
    string,
    BigNumber,
    string,
    DataTypes.EIP712SignatureStructOutput
  ] & {
    user: string;
    profileId: BigNumber;
    metadata: string;
    sig: DataTypes.EIP712SignatureStructOutput;
  };

  export type ToggleFollowWithSigDataStruct = {
    follower: string;
    profileIds: BigNumberish[];
    enables: boolean[];
    sig: DataTypes.EIP712SignatureStruct;
  };

  export type ToggleFollowWithSigDataStructOutput = [
    string,
    BigNumber[],
    boolean[],
    DataTypes.EIP712SignatureStructOutput
  ] & {
    follower: string;
    profileIds: BigNumber[];
    enables: boolean[];
    sig: DataTypes.EIP712SignatureStructOutput;
  };
}

export interface LensPeripheryInterface extends utils.Interface {
  contractName: "LensPeriphery";
  functions: {
    "HUB()": FunctionFragment;
    "NAME()": FunctionFragment;
    "dispatcherSetProfileMetadataURI(uint256,string)": FunctionFragment;
    "getProfileMetadataURI(uint256)": FunctionFragment;
    "getProfileMetadataURIByOwner(address,uint256)": FunctionFragment;
    "setProfileMetadataURI(uint256,string)": FunctionFragment;
    "setProfileMetadataURIWithSig((address,uint256,string,(uint8,bytes32,bytes32,uint256)))": FunctionFragment;
    "sigNonces(address)": FunctionFragment;
    "toggleFollow(uint256[],bool[])": FunctionFragment;
    "toggleFollowWithSig((address,uint256[],bool[],(uint8,bytes32,bytes32,uint256)))": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "HUB", values?: undefined): string;
  encodeFunctionData(functionFragment: "NAME", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "dispatcherSetProfileMetadataURI",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getProfileMetadataURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProfileMetadataURIByOwner",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setProfileMetadataURI",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setProfileMetadataURIWithSig",
    values: [DataTypes.SetProfileMetadataWithSigDataStruct]
  ): string;
  encodeFunctionData(functionFragment: "sigNonces", values: [string]): string;
  encodeFunctionData(
    functionFragment: "toggleFollow",
    values: [BigNumberish[], boolean[]]
  ): string;
  encodeFunctionData(
    functionFragment: "toggleFollowWithSig",
    values: [DataTypes.ToggleFollowWithSigDataStruct]
  ): string;

  decodeFunctionResult(functionFragment: "HUB", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "NAME", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "dispatcherSetProfileMetadataURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProfileMetadataURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProfileMetadataURIByOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProfileMetadataURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProfileMetadataURIWithSig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sigNonces", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "toggleFollow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggleFollowWithSig",
    data: BytesLike
  ): Result;

  events: {};
}

export interface LensPeriphery extends BaseContract {
  contractName: "LensPeriphery";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LensPeripheryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    HUB(overrides?: CallOverrides): Promise<[string]>;

    NAME(overrides?: CallOverrides): Promise<[string]>;

    dispatcherSetProfileMetadataURI(
      profileId: BigNumberish,
      metadata: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getProfileMetadataURI(
      profileId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getProfileMetadataURIByOwner(
      user: string,
      profileId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    setProfileMetadataURI(
      profileId: BigNumberish,
      metadata: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setProfileMetadataURIWithSig(
      vars: DataTypes.SetProfileMetadataWithSigDataStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    sigNonces(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    toggleFollow(
      profileIds: BigNumberish[],
      enables: boolean[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    toggleFollowWithSig(
      vars: DataTypes.ToggleFollowWithSigDataStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  HUB(overrides?: CallOverrides): Promise<string>;

  NAME(overrides?: CallOverrides): Promise<string>;

  dispatcherSetProfileMetadataURI(
    profileId: BigNumberish,
    metadata: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getProfileMetadataURI(
    profileId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getProfileMetadataURIByOwner(
    user: string,
    profileId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  setProfileMetadataURI(
    profileId: BigNumberish,
    metadata: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setProfileMetadataURIWithSig(
    vars: DataTypes.SetProfileMetadataWithSigDataStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  sigNonces(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  toggleFollow(
    profileIds: BigNumberish[],
    enables: boolean[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  toggleFollowWithSig(
    vars: DataTypes.ToggleFollowWithSigDataStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    HUB(overrides?: CallOverrides): Promise<string>;

    NAME(overrides?: CallOverrides): Promise<string>;

    dispatcherSetProfileMetadataURI(
      profileId: BigNumberish,
      metadata: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getProfileMetadataURI(
      profileId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getProfileMetadataURIByOwner(
      user: string,
      profileId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    setProfileMetadataURI(
      profileId: BigNumberish,
      metadata: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setProfileMetadataURIWithSig(
      vars: DataTypes.SetProfileMetadataWithSigDataStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    sigNonces(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    toggleFollow(
      profileIds: BigNumberish[],
      enables: boolean[],
      overrides?: CallOverrides
    ): Promise<void>;

    toggleFollowWithSig(
      vars: DataTypes.ToggleFollowWithSigDataStruct,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    HUB(overrides?: CallOverrides): Promise<BigNumber>;

    NAME(overrides?: CallOverrides): Promise<BigNumber>;

    dispatcherSetProfileMetadataURI(
      profileId: BigNumberish,
      metadata: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getProfileMetadataURI(
      profileId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getProfileMetadataURIByOwner(
      user: string,
      profileId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setProfileMetadataURI(
      profileId: BigNumberish,
      metadata: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setProfileMetadataURIWithSig(
      vars: DataTypes.SetProfileMetadataWithSigDataStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    sigNonces(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    toggleFollow(
      profileIds: BigNumberish[],
      enables: boolean[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    toggleFollowWithSig(
      vars: DataTypes.ToggleFollowWithSigDataStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    HUB(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    NAME(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    dispatcherSetProfileMetadataURI(
      profileId: BigNumberish,
      metadata: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getProfileMetadataURI(
      profileId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getProfileMetadataURIByOwner(
      user: string,
      profileId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setProfileMetadataURI(
      profileId: BigNumberish,
      metadata: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setProfileMetadataURIWithSig(
      vars: DataTypes.SetProfileMetadataWithSigDataStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    sigNonces(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    toggleFollow(
      profileIds: BigNumberish[],
      enables: boolean[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    toggleFollowWithSig(
      vars: DataTypes.ToggleFollowWithSigDataStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
