[package]
name = "wired-protocol-proto"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
bytes = "1.5.0"
prost = "0.12.2"

[build-dependencies]
prost-build = "0.12.2"
