CREATE DATABASE
  UserDatabase;

GRANT
  ALL PRIVILEGES ON DATABASE UserDatabase TO postgres;

CREATE TABLE
  Users(UserID SERIAL PRIMARY KEY, Address CHAR(42));

CREATE TABLE
  Projects(
    ProjectID SERIAL PRIMARY KEY,
    Name VARCHAR(255),
    Description VARCHAR(2040),
    CONSTRAINT Owner FOREIGN KEY (OwnerID) REFERENCES Users(OwnerID) ON DELETE CASCADE
  );