[package]
edition.workspace    = true
license.workspace    = true
name                 = "wired-schemas"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[dependencies]
blake3.workspace = true
bytes.workspace  = true
ron.workspace    = true
wds-schema       = { default-features = false, path = "../wds-schema" }
