[package]
edition.workspace    = true
license.workspace    = true
name                 = "bevy-msdf"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[dependencies]
bevy.workspace      = true
image               = { features = ["png"], workspace = true }
msdf                = { path = "../msdf" }
thiserror.workspace = true
smol_str.workspace  = true

[dev-dependencies]
bevy_panorbit_camera.workspace = true
notosans                       = { version = "0.1.0" }
naga                           = { default-features = false, features = ["wgsl-in"], version = "29.0.4" }
