[package]
edition.workspace    = true
license.workspace    = true
name                 = "bevy-msdf"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[dependencies]
bevy.workspace      = true
image               = { features = ["png"], workspace = true }
msdf                = { path = "../msdf" }
smol_str.workspace  = true
thiserror.workspace = true

[dev-dependencies]
bevy_panorbit_camera.workspace = true
naga.workspace                 = true
notosans.workspace             = true
