[package]
edition.workspace    = true
license.workspace    = true
name                 = "wired-prelude"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
wired-kv.path    = "../wired-kv"
wired-math.path  = "../wired-math"
wired-scene.path = "../wired-scene"
