package wired:peer;

world all {
  import api;
  import types;
}

interface types {
  type peer-id = list<u8>;
}

interface api {
  use types.{peer-id};
  use wired:scene/types.{document-id};
  use wired:error/types.{error};

  self-peer:     func() -> result<option<peer-id>, error>;
  self-did:      func() -> result<option<string>, error>;
  doc-owner:     func(doc: document-id) -> result<option<peer-id>, error>;
  is-self-owner: func() -> result<bool, error>;
}
