[package]
edition.workspace    = true
license.workspace    = true
name                 = "unavi-assets-fetch"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[dependencies]
bevy.workspace        = true
bevy-iroh-assets.path = "../bevy-iroh-assets"
bevy-msdf.path        = "../bevy-msdf"
unavi-assets.path     = "../unavi-assets"
