[package]
edition.workspace    = true
license.workspace    = true
name                 = "unavi-default-home"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
blake3.workspace       = true
unavi-script-util.path = "../unavi-script-util"
wired-prelude.path     = "../wired-prelude"
wit-bindgen.workspace  = true
