package unavi:vui-module;

world guest {
  include wired:prelude/lib;
  export api;
}

interface api {
  use wired:math/types.{transform};
  use wired:scene/types.{color, prim, prim-id};

  variant module-event {
    activate(transform),
    deactivate,
    set-color(color),
  }

  resource vui-module {
    // `icon` should be a prim carrying a `mesh` attribute that will be
    // rendered as the module's gauntlet icon.
    constructor(name: string, icon: borrow<prim>);
    poll: func() -> option<module-event>;
  }

  record registered-module {
    doc-id:       list<u8>,
    name:         string,
    icon-prim-id: prim-id,
  }

  resource vui-module-registry {
    constructor();
    poll: func() -> list<registered-module>;
    activate: func(doc-id: list<u8>, transform: transform);
    deactivate: func(doc-id: list<u8>);
    set-color: func(doc-id: list<u8>, color: color);
  }
}
