[package]
edition.workspace    = true
license.workspace    = true
name                 = "test-stall"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen.workspace = true
