package unavi:shapes;

world shapes {
    import wired:scene/mesh;

    export api;
}

interface api {
  use wired:scene/mesh.{mesh};
  use wired:math/types.{vec3};

  create-cuboid: func(size: vec3) -> mesh;

  // Creates a UV sphere with the given number of
  // longitudinal sectors and latitudinal stacks, aka horizontal and vertical resolution.
  // 
  // A good default is `32` sectors and `18` stacks.
  create-sphere: func(radius: f32, sectors: u32, stacks: u32) -> mesh;
}
