package unavi:shapes;

world shapes {
    import wired:log/api;
    import wired:scene/mesh;

    import api;
    export api;
}

interface api {
  use wired:math/types.{vec3};
  use wired:scene/mesh.{mesh};
  use wired:scene/node.{node};

  resource cuboid {
    constructor(size: vec3);

    size: func() -> vec3;
    set-size: func(value: vec3);

    // Creates a mesh of this shape.
    to-mesh: func() -> mesh;
    // Creates a node with a mesh of this shape.
    to-node: func() -> node;
    // Creates a node with a mesh and physics collider of this shape.
    to-physics-node: func() -> node;
  }

  record sphere-ico {
    subdivisions: u8
  }

  record sphere-uv {
    sectors: u8,
    stacks: u8,
  }

  variant sphere-kind {
    // An icosphere, a spherical mesh that consists of similar sized triangles.
    ico(sphere-ico),
    // A UV sphere, a spherical mesh that consists of quadrilaterals
    uv(sphere-uv),
  }

  resource sphere {
    new-ico: static func(radius: f32) -> sphere;
    new-uv: static func(radius: f32) -> sphere;

    radius: func() -> f32;
    set-radius: func(value: f32);

    kind: func() -> sphere-kind;
    set-kind: func(value: sphere-kind);

    // Creates a mesh of this shape.
    to-mesh: func() -> mesh;
    // Creates a node with a mesh of this shape.
    to-node: func() -> node;
    // Creates a node with a mesh and physics collider of this shape.
    to-physics-node: func() -> node;
  }
}
