name: CD

on:
  push:
    branches:
      - main

jobs:
  deployment-server:
    runs-on: server

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: yarn install
      - run: pm2 restart server
