name: Deploy
on:
  workflow_dispatch:
    inputs:
      ref:
        description: git ref to deploy
        required: false
        type: string
  workflow_call:
    inputs:
      ref:
        description: git ref to deploy
        required: false
        type: string
concurrency:
  group: deploy
  cancel-in-progress: false
jobs:
  unavi-server:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: AdityaGarg8/remove-unwanted-software@v4
        with:
          remove-android: true
          remove-cached-tools: true
          remove-codeql: true
          remove-docker-images: true
          remove-dotnet: true
          remove-haskell: true
          remove-large-packages: true
      - uses: actions/checkout@v7
        with:
          ref: ${{ inputs.ref || github.ref }}
      - uses: DeterminateSystems/determinate-nix-action@v3
        with:
          extra-conf: |
            extra-experimental-features = pipe-operators
            extra-substituters = file://${{ github.workspace }}/nix-cache
            require-sigs = false
      - name: Fetch build-nix deploy cache
        run: mkdir -p nix-cache
      - uses: actions/download-artifact@v8
        continue-on-error: true
        with:
          pattern: nix-cache-*
          path: nix-cache
          merge-multiple: true
      - name: Get deploy info
        id: deploy_info
        run: |
          SERVER_IP=$(jq -r '.stable.server_ipv4' infra/terraform/deploy.json)
          echo "server_ip=$SERVER_IP" >> "$GITHUB_OUTPUT"
      - name: Setup ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan ${{ steps.deploy_info.outputs.server_ip }} >> ~/.ssh/known_hosts
      - name: Deploy
        run: nix develop --command env -u LD_LIBRARY_PATH deploy .#unavi-stable
